export const FETCH_PHONES ='FETCH_PHONES';
export const PHONE_SELECTED='PHONE_SELECTED';
export const CLOSE_OVERLAY='CLOSE_OVERLAY';
export const SELECT_BRAND='SELECT_BRAND';
export const DESELECT_BRAND='DESELECT_BRAND';
